<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
        <ImplicitUsings>enable</ImplicitUsings>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        <OutputPath>..\Widgets</OutputPath>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Lab04.Contracts\Lab04.Contracts.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="System.Composition" Version="9.0.9" />
    </ItemGroup>

</Project>
