<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
      <Compile Include="Signatures.fs" />
      <Compile Include="Stocks.fsx" />
      <Compile Include="StockAnalyzer.fs" />
      <Compile Include="Sums.fsx" />
      <Compile Include="TypesTest.fsx" />
      <Compile Include="Types\String50.fs" />
      <Compile Include="Types\WrappedString.fs" />
      <Compile Include="Types\EmailAddress.fs" />
      <Compile Include="Types\ContactInfo.fs" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FSharp.Collections.ParallelSeq" Version="1.2.0" />
      <PackageReference Include="XPlot.Plotly" Version="4.1.0" />
    </ItemGroup>

</Project>
